# Generated by Django 6.0.4 on 2026-04-10 21:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CierreDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('saldo_inicial_caja', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('total_ingresos', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('total_egresos', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('saldo_final_caja', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Empresa', max_length=200)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('giro', models.CharField(blank=True, max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('moneda', models.CharField(default='CLP', max_length=5)),
                ('saldo_inicial_caja', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('saldo_inicial_banco', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('fecha_inicio_operaciones', models.DateField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('costo', 'Costo de Venta')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoDiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('ingreso_caja', 'Ingreso Caja'), ('egreso_caja', 'Egreso Caja'), ('ingreso_banco', 'Ingreso Banco'), ('egreso_banco', 'Egreso Banco'), ('suma_boletas', 'Suma de Boletas'), ('suma_facturas_emitidas', 'Suma Facturas Emitidas'), ('suma_facturas_recibidas', 'Suma Facturas Recibidas (Compras)'), ('remuneracion', 'Remuneración / Sueldos'), ('impuesto', 'Pago Impuesto / Contribución'), ('prestamo_recibido', 'Préstamo Recibido'), ('pago_prestamo', 'Pago Préstamo / Cuota'), ('inversion', 'Inversión / Activo Fijo'), ('otro_ingreso', 'Otro Ingreso'), ('otro_egreso', 'Otro Egreso')], max_length=40)),
                ('descripcion', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=14)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta_debito', 'Tarjeta Débito'), ('tarjeta_credito', 'Tarjeta Crédito'), ('nota_credito', 'Nota de Crédito'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('cantidad_documentos', models.IntegerField(blank=True, help_text='Nº de boletas o facturas agrupadas', null=True)),
                ('rut_contraparte', models.CharField(blank=True, help_text='RUT cliente o proveedor', max_length=20)),
                ('nombre_contraparte', models.CharField(blank=True, max_length=150)),
                ('monto_neto', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('monto_iva', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.centrocosto')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Movimiento Diario',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('categoria', models.CharField(choices=[('ventas', 'Ventas / Ingresos'), ('costo_venta', 'Costo de Ventas'), ('remuneraciones', 'Remuneraciones'), ('arriendo', 'Arriendo'), ('servicios_basicos', 'Servicios Básicos'), ('marketing', 'Marketing / Publicidad'), ('logistica', 'Logística / Transporte'), ('impuestos', 'Impuestos'), ('financiero', 'Gastos Financieros'), ('otros_gastos', 'Otros Gastos')], max_length=30)),
                ('monto_presupuestado', models.DecimalField(decimal_places=0, max_digits=14)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-anio', '-mes', 'categoria'],
                'unique_together': {('anio', 'mes', 'categoria')},
            },
        ),
    ]
