# Generated by Django 6.0.4 on 2026-04-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0003_tc_pendiente"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="movimientodiario",
            new_name="contabilida_fecha_0d7ee6_idx",
            old_name="mov_fecha_cuenta_idx",
        ),
        migrations.RenameIndex(
            model_name="movimientodiario",
            new_name="contabilida_categor_cb7cf0_idx",
            old_name="mov_categoria_idx",
        ),
        migrations.RenameIndex(
            model_name="movimientodiario",
            new_name="contabilida_es_tran_7acad4_idx",
            old_name="mov_interna_idx",
        ),
        migrations.AlterField(
            model_name="cierrediario",
            name="saldo_final_caja",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="cierrediario",
            name="saldo_inicial_caja",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="cierrediario",
            name="total_egresos",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="cierrediario",
            name="total_ingresos",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="configuracionempresa",
            name="saldo_inicial_banco",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="configuracionempresa",
            name="saldo_inicial_caja",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="movimientodiario",
            name="cantidad_documentos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movimientodiario",
            name="monto",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name="movimientodiario",
            name="monto_iva",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="movimientodiario",
            name="monto_neto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="movimientodiario",
            name="rut_contraparte",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="movimientodiario",
            name="tc_pendiente",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="presupuestomensual",
            name="monto_presupuestado",
            field=models.DecimalField(decimal_places=0, max_digits=18),
        ),
    ]
